name: Deploy Documentation

on:
  workflow_dispatch:

  push:
    branches: [main]
    paths:
      - 'docs/**'

jobs:
  publish-documentation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'

      - name: Install packages and build
        run: |
          pushd ./docs
          bun install --yarn
          bun run build
          popd

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
          publish_branch: gh-pages
          cname: expo-iap.hyo.dev
